title: The Berry Basket
permalink: pretty

collections:
    projects:
        output: false
#        order:
#            - tally.md
#            - fitgpt.md
#            - nerf-ballista.md
#            - polytopia-remake.md
#            - racket-clip.md
